export const productData = [
  {
    name: 'Moisturizing Facial Cream',
    category: 'Skincare',
    description:
      'A rich moisturizing cream that hydrates and nourishes dry skin.',
    price: 25.99,
    stock: 150,
    brand: 'GlowUp',
    ingredients: ['Aloe Vera', 'Shea Butter', 'Vitamin E'],
    skinType: 'Dry',
    size: '50ml',
    rating: 4.7,
  },
  {
    name: 'Anti-Aging Serum',
    category: 'Skincare',
    description: 'A powerful serum that reduces fine lines and wrinkles.',
    price: 45.0,
    stock: 100,
    brand: 'Youthful Glow',
    ingredients: ['Retinol', 'Hyaluronic Acid', 'Peptides'],
    skinType: 'Mature',
    size: '30ml',
    rating: 4.9,
  },
  {
    name: 'Vitamin C Face Mask',
    category: 'Skincare',
    description: 'A rejuvenating mask that brightens and evens out skin tone.',
    price: 18.5,
    stock: 200,
    brand: 'Radiant Glow',
    ingredients: ['Vitamin C', 'Lemon Extract', 'Kaolin Clay'],
    skinType: 'All Skin Types',
    size: '100g',
    rating: 4.8,
  },
  {
    name: 'Liquid Foundation',
    category: 'Makeup',
    description:
      'A full-coverage foundation that provides a flawless, natural finish.',
    price: 22.99,
    stock: 250,
    brand: 'Flawless Finish',
    shade: 'Ivory',
    skinType: 'Oily/Combination',
    size: '30ml',
    coverage: 'Full',
    finish: 'Matte',
    rating: 4.6,
  },
  {
    name: 'Waterproof Mascara',
    category: 'Makeup',
    description:
      'A smudge-proof mascara that defines and lengthens lashes for all-day wear.',
    price: 15.99,
    stock: 180,
    brand: 'LashX',
    shade: 'Black',
    size: '10g',
    rating: 4.8,
  },
  {
    name: 'Red Matte Lipstick',
    category: 'Makeup',
    description:
      'A bold red lipstick with a smooth matte finish that lasts all day.',
    price: 12.99,
    stock: 300,
    brand: 'Glamour Lips',
    shade: 'Red Fury',
    size: '4g',
    finish: 'Matte',
    rating: 4.7,
  },
  {
    name: 'Floral Eau de Parfum',
    category: 'Fragrance',
    description:
      'A light, floral fragrance with hints of rose, jasmine, and sandalwood.',
    price: 55.0,
    stock: 120,
    brand: 'Scent Essence',
    size: '50ml',
    notes: ['Rose', 'Jasmine', 'Sandalwood'],
    occasion: 'Daytime',
    rating: 4.9,
  },
  {
    name: 'Woody Oud Perfume',
    category: 'Fragrance',
    description:
      'A luxurious fragrance with deep woody and musky notes of oud.',
    price: 75.0,
    stock: 80,
    brand: 'Luxury Scents',
    size: '100ml',
    notes: ['Oud', 'Saffron', 'Amber'],
    occasion: 'Evening',
    rating: 4.8,
  },
  {
    name: 'Citrus Fresh Cologne',
    category: 'Fragrance',
    description:
      'A refreshing fragrance with citrus notes that energizes and refreshes.',
    price: 40.0,
    stock: 150,
    brand: 'FreshVibe',
    size: '75ml',
    notes: ['Lemon', 'Grapefruit', 'Mint'],
    occasion: 'Casual',
    rating: 4.7,
  },
];
